# Site settings
title: Don Galdino
email: contato@dongaldino.com.br
url: https://www.dongaldino.com.br
description: "Bar & Restaurante" #. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  verde: '#009a65'
  vermelho: '#d92636'

# Footer settings
footer: Don Galdino | Gawiga

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/dongaldino/
  - title: facebook
    url: http://www.facebook.com/dongaldinobistro
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
